import tkinter as tk
from tkinter import ttk

def mostrar():
    v_min_w="800"
    v_min_h="600"
    detalles_pady=5
    v=tk.Tk()
    v.title("UOCRA PY")
    v.geometry(f"{v_min_w}x{v_min_h}")
    v.resizable(width=False, height=False)
    # DEFINICIONES
    f_personas = tk.Frame(v)
    # EMPLEADORES DEFINICIONES
    f_empleadores = tk.Frame(f_personas)
    l_empleadores = tk.Label(f_empleadores, text="Empleadores")
    tview_empleadores = ttk.Treeview(f_empleadores, height=8)
    f_empleador_botones = tk.Frame(f_empleadores)
    b_empleador_quitar = tk.Button(f_empleador_botones, text="Quitar")
    b_empleador_agregar = tk.Button(f_empleador_botones, text="Agregar")
    # EMPLEADOS DEFINICIONES
    f_empleados = tk.Frame(f_personas)
    l_empleados = tk.Label(f_empleados, text="Empleados")
    tview_empleados = ttk.Treeview(f_empleados, height=8)
    f_empleados_botones = tk.Frame(f_empleados)
    b_empleado_quitar = tk.Button(f_empleados_botones, text="Quitar")
    b_empleado_agregar = tk.Button(f_empleados_botones, text="Agregar")
    # DETALLES DEFINICIONES
    f_detalles = tk.Frame(v)
    f_nombre = tk.Frame(f_detalles)
    l_nombre = tk.Label(f_nombre, text="Nombre:",width=25, anchor=tk.W)
    t_nombre = tk.Text(f_nombre,height=1, width=40)
    f_cuil = tk.Frame(f_detalles)
    l_cuil = tk.Label(f_cuil, text="CUIL:", width=25, anchor=tk.W)
    t_cuil = tk.Text(f_cuil, height=1, width=13)
    f_afiliado = tk.Frame(f_detalles)
    l_afiliado = tk.Label(f_afiliado, text="Afiliado:", width=25, anchor=tk.W)
    t_afiliado = tk.Text(f_afiliado, height=1, width=1)
    f_rem_cuota_sind = tk.Frame(f_detalles)
    l_rem_cuota_sind = tk.Label(f_rem_cuota_sind, text="Remunerac. cuota sind.:", width=25, anchor=tk.W)
    t_rem_cuota_sind = tk.Text(f_rem_cuota_sind, height=1, width=13)
    f_rem_cese_laboral = tk.Frame(f_detalles)
    l_rem_cese_laboral = tk.Label(f_rem_cese_laboral, text="Remunerac. cese laboral.:", width=25, anchor=tk.W)
    t_rem_cese_laboral = tk.Text(f_rem_cese_laboral, height=1, width=13)
    f_ingreso = tk.Frame(f_detalles)
    l_ingreso = tk.Label(f_ingreso, text="Ingreso:", width=25, anchor=tk.W)
    t_ingreso = tk.Text(f_ingreso, height=1, width=10)
    f_codigo_postal = tk.Frame(f_detalles)
    l_codigo_postal = tk.Label(f_codigo_postal, text="Codigo Postal:", width=25, anchor=tk.W)
    t_codigo_postal = tk.Text(f_codigo_postal, height=1, width=4)
    f_convenio = tk.Frame(f_detalles)
    l_convenio = tk.Label(f_convenio, text="Convenio:", width=25, anchor=tk.W)
    t_convenio = tk.Text(f_convenio, height=1, width=2)
    f_categoria= tk.Frame(f_detalles)
    l_categoria = tk.Label(f_categoria, text="Categoria:", width=25, anchor=tk.W)
    t_categoria = tk.Text(f_categoria, height=1, width=2)
    f_admin_publica = tk.Frame(f_detalles)
    l_admin_publica = tk.Label(f_admin_publica, text="Admin. Publica:", width=25, anchor=tk.W)
    t_admin_publica = tk.Text(f_admin_publica, height=1, width=1)
    f_detalles_botones = tk.Frame(f_detalles)
    l_detalles_status = tk.Label(f_detalles_botones, text="", width=20, anchor=tk.W)
    b_detalles_guardar = tk.Button(f_detalles_botones, text="Guardar cambios")
    f_exportacion = tk.Frame(v)
    l_exportacion = tk.Label(f_exportacion, text="Exportando para:", width=48, anchor=tk.W)
    b_exportacion = tk.Button(f_exportacion, text="Exportar a UOCRA...")
    # PACKS
    f_personas.pack(side=tk.LEFT, padx=(20,10))
    # EMPLEADORES PACK
    f_empleadores.pack(side=tk.TOP, pady=(0,20))
    l_empleadores.pack(side=tk.TOP)
    tview_empleadores.pack(side=tk.TOP)
    f_empleador_botones.pack(side=tk.TOP)
    b_empleador_quitar.pack(side=tk.LEFT)
    b_empleador_agregar.pack(side=tk.LEFT)
    # EMPLEADOS PACK
    f_empleados.pack(side=tk.TOP, pady=(20,0))
    l_empleados.pack(side=tk.TOP)
    tview_empleados.pack(side=tk.TOP)
    f_empleados_botones.pack(side=tk.TOP)
    b_empleado_quitar.pack(side=tk.LEFT)
    b_empleado_agregar.pack(side=tk.LEFT)
    # DETALLES PACK
    f_detalles.pack(side=tk.TOP, padx=(40,10),pady=(50,10))
    f_nombre.pack(side=tk.TOP, anchor=tk.W, pady=(detalles_pady,detalles_pady))
    l_nombre.pack(side=tk.LEFT)
    t_nombre.pack(side=tk.LEFT)
    f_cuil.pack(side=tk.TOP, anchor=tk.W, pady=(detalles_pady,detalles_pady))
    l_cuil.pack(side=tk.LEFT, anchor=tk.W)
    t_cuil.pack(side=tk.LEFT)
    f_afiliado.pack(side=tk.TOP, anchor=tk.W, pady=(detalles_pady,detalles_pady))
    l_afiliado.pack(side=tk.LEFT, anchor=tk.W)
    t_afiliado.pack(side=tk.LEFT)
    f_rem_cuota_sind.pack(side=tk.TOP, anchor=tk.W, pady=(detalles_pady,detalles_pady))
    l_rem_cuota_sind.pack(side=tk.LEFT, anchor=tk.W)
    t_rem_cuota_sind.pack(side=tk.LEFT)
    f_rem_cese_laboral.pack(side=tk.TOP, anchor=tk.W, pady=(detalles_pady,detalles_pady))
    l_rem_cese_laboral.pack(side=tk.LEFT, anchor=tk.W)
    t_rem_cese_laboral.pack(side=tk.LEFT)
    f_ingreso.pack(side=tk.TOP, anchor=tk.W, pady=(detalles_pady,detalles_pady))
    l_ingreso.pack(side=tk.LEFT, anchor=tk.W)
    t_ingreso.pack(side=tk.LEFT)
    f_codigo_postal.pack(side=tk.TOP, anchor=tk.W, pady=(detalles_pady,detalles_pady))
    l_codigo_postal.pack(side=tk.LEFT, anchor=tk.W)
    t_codigo_postal.pack(side=tk.LEFT)
    f_convenio.pack(side=tk.TOP, anchor=tk.W, pady=(detalles_pady,detalles_pady))
    l_convenio.pack(side=tk.LEFT, anchor=tk.W)
    t_convenio.pack(side=tk.LEFT)
    f_categoria.pack(side=tk.TOP, anchor=tk.W, pady=(detalles_pady,detalles_pady))
    l_categoria.pack(side=tk.LEFT, anchor=tk.W)
    t_categoria.pack(side=tk.LEFT)
    f_admin_publica.pack(side=tk.TOP, anchor=tk.W, pady=(detalles_pady,detalles_pady))
    l_admin_publica.pack(side=tk.LEFT, anchor=tk.W)
    t_admin_publica.pack(side=tk.LEFT)
    f_detalles_botones.pack(side=tk.TOP, pady=(40,20))
    l_detalles_status.pack(side=tk.LEFT, anchor=tk.W)
    b_detalles_guardar.pack(side=tk.LEFT, anchor=tk.W)
    # EXPORTACION PACK
    f_exportacion.pack(side=tk.RIGHT, anchor=tk.S, padx=(0,25), pady=(0,25))
    l_exportacion.pack(side=tk.LEFT, padx=(0,25))
    b_exportacion.pack(side=tk.RIGHT)
    #b_exportacion.pack(side=tk.RIGHT, anchor=tk.S, padx=(0,25), pady=(0,25))

    v.mainloop()


mostrar()
